# Generated by Django 4.1.6 on 2023-02-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("miles_per_gallon", models.IntegerField(default=0)),
                ("cylinders", models.IntegerField(default=0)),
                ("displacement", models.CharField(max_length=20)),
                ("horsepower", models.IntegerField(default=0)),
                ("drat", models.FloatField()),
                ("weight", models.IntegerField()),
                ("quarter_mile", models.FloatField()),
                (
                    "configuration",
                    models.IntegerField(choices=[(0, "V"), (1, "Straight")]),
                ),
                (
                    "transmission",
                    models.IntegerField(choices=[(0, "Automatic"), (1, "Manual")]),
                ),
                ("gears", models.IntegerField()),
                ("carburetors", models.IntegerField()),
            ],
        ),
    ]
