# Generated by Django 4.1.6 on 2023-02-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0002_alter_car_miles_per_gallon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="weight",
            field=models.FloatField(),
        ),
    ]
